version: '3.8'

services:
  app:
    # build:
    #   context: .          
    #   dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    # depends_on:
    #   - mongodb
    #   - redis
    # environment:
    #   - MONGO_URL=mongodb://mongodb:27017/user
    # volumes:
    #   - .:/usr/src/app   
    # command: npm run start

  mongodb:
    image: mongo:5.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"

volumes:
  mongo_data:
